# Generated by Django 4.2.9 on 2024-01-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0003_category_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
