# Generated by Django 4.2.9 on 2024-02-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0008_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pics/default_image.png', upload_to='profile_pics/'),
        ),
    ]
